name: Upload Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry --user
        poetry install
    - name: Run unit tests
      run: |
        poetry run python -m unittest ./tests/main_test.py
    - name: Build package
      if: github.ref == 'refs/heads/main'
      run: peotry publish --build --username azeaze --password zaeazaze
